export const cocoNames = [
  "person", "bicycle", "car", "motorcycle", "airplane", "bus", "train", "truck", "boat",
  "traffic light", "fire hydrant", "stop sign", "parking meter", "bench", "bird", "cat", "dog",
  "horse", "sheep", "cow", "elephant", "bear", "zebra", "giraffe", "backpack", "umbrella",
  "handbag", "tie", "suitcase", "frisbee", "skis", "snowboard", "sports ball", "kite",
  "baseball bat", "baseball glove", "skateboard", "surfboard", "tennis racket", "bottle",
  "wine glass", "cup", "fork", "knife", "spoon", "bowl", "banana", "apple", "sandwich", "orange",
  "broccoli", "carrot", "hot dog", "pizza", "donut", "cake", "chair", "couch", "potted plant",
  "bed", "dining table", "toilet", "tv", "laptop", "mouse", "remote", "keyboard", "cell phone",
  "microwave", "oven", "toaster", "sink", "refrigerator", "book", "clock", "vase", "scissors",
  "teddy bear", "hair drier", "toothbrush"
];

export const translationTable: { [key: string]: string } = {
  "persona": "person",
  "personas": "person",
  "gente": "person",
  "auto": "car",
  "autos": "car",
  "coche": "car",
  "coches": "car",
  "bicicleta": "bicycle",
  "bicicletas": "bicycle",
  "moto": "motorcycle",
  "motos": "motorcycle",
  "avión": "airplane",
  "aviones": "airplane",
  "autobús": "bus",
  "autobuses": "bus",
  "camión": "truck",
  "camiones": "truck",
  "barco": "boat",
  "semáforo": "traffic light",
  "hidrante": "fire hydrant",
  "señal de pare": "stop sign",
  "parquímetro": "parking meter",
  "banco": "bench",
  "pájaro": "bird",
  "pájaros": "bird",
  "gato": "cat",
  "gatos": "cat",
  "perro": "dog",
  "perros": "dog",
  "caballo": "horse",
  "caballos": "horse",
  "oveja": "sheep",
  "ovejas": "sheep",
  "vaca": "cow",
  "vacas": "cow",
  "elefante": "elephant",
  "elefantes": "elephant",
  "oso": "bear",
  "osos": "bear",
  "cebra": "zebra",
  "cebras": "zebra",
  "jirafa": "giraffe",
  "jirafas": "giraffe",
  "mochila": "backpack",
  "paraguas": "umbrella",
  "cartera": "handbag",
  "corbata": "tie",
  "maleta": "suitcase",
  "frisbee": "frisbee",
  "esquís": "skis",
  "snowboard": "snowboard",
  "pelota": "sports ball",
  "cometa": "kite",
  "bate": "baseball bat",
  "guante": "baseball glove",
  "monopatín": "skateboard",
  "tabla de surf": "surfboard",
  "raqueta": "tennis racket",
  "botella": "bottle",
  "vaso": "cup",
  "tenedor": "fork",
  "cuchillo": "knife",
  "cuchara": "spoon",
  "plato": "bowl",
  "banana": "banana",
  "manzana": "apple",
  "sándwich": "sandwich",
  "naranja": "orange",
  "brócoli": "broccoli",
  "zanahoria": "carrot",
  "hot dog": "hot dog",
  "pizza": "pizza",
  "donut": "donut",
  "pastel": "cake",
  "silla": "chair",
  "sofá": "couch",
  "planta": "potted plant",
  "cama": "bed",
  "mesa": "dining table",
  "inodoro": "toilet",
  "televisor": "tv",
  "laptop": "laptop",
  "ratón": "mouse",
  "control": "remote",
  "teclado": "keyboard",
  "celular": "cell phone",
  "microondas": "microwave",
  "horno": "oven",
  "tostadora": "toaster",
  "fregadero": "sink",
  "refrigerador": "refrigerator",
  "libro": "book",
  "reloj": "clock",
  "jarrón": "vase",
  "tijeras": "scissors",
  "peluche": "teddy bear",
  "secador": "hair drier",
  "cepillo de dientes": "toothbrush"
};
